### ISSUE TITLE
function call with bytes parameters cannot pass the quicktest

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#25]
<a href="https://github.com/HackFisher"><img src="https://avatars1.githubusercontent.com/u/1070122?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HackFisher](https://github.com/HackFisher)**
_Thursday Nov 16, 2017 at 08:22 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/65_

----

Following code is in the solidity contract, where the "_data" is type of bytes.

```
receiver.call.value(0)(bytes4(keccak256(_custom_fallback)), msg.sender, _amount, _data);
```

Fail when running "dapp test" with tests run this code.

```
/Users/user/github.com/dapphub/dapp/libexec/dapp/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
              ^

Error: Number can only safely store up to 53 bits
    at assert (/Users/user/github.com/dapphub/dapp/libexec/dapp/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/user/github.com/dapphub/dapp/libexec/dapp/node_modules/bn.js/lib/bn.js:506:7)
    at decodeSingle (/Users/user/github.com/dapphub/dapp/libexec/dapp/node_modules/ethereumjs-abi/lib/index.js:250:54)
    at Function.ABI.rawDecode (/Users/user/github.com/dapphub/dapp/libexec/dapp/node_modules/ethereumjs-abi/lib/index.js:367:14)
    at formatMethodCall (/Users/user/github.com/dapphub/dapp/libexec/dapp/dapp-quicktest:277:44)
    at formatTrace (/Users/user/github.com/dapphub/dapp/libexec/dapp/dapp-quicktest:292:152)
    at Array.forEach (<anonymous>)
    at failedTest.results.forEach.x (/Users/user/github.com/dapphub/dapp/libexec/dapp/dapp-quicktest:214:43)
    at Array.forEach (<anonymous>)
    at printFailure (/Users/user/github.com/dapphub/dapp/libexec/dapp/dapp-quicktest:214:22)
make: *** [test] Error 1
```

**Comment by mbrock** [comment]
<a href="https://github.com/nmushegian"><img src="https://avatars0.githubusercontent.com/u/924397?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nmushegian](https://github.com/nmushegian)**
_Sunday Nov 19, 2017 at 17:12 GMT_

----

This might have to do with the way solidity interprets multiple data arguments in `.call`. If all your tools are up to date then you'll have to tell the solidity guys to add support for this, and then pack your calldata manually.

Can you give some more context?

**Comment by mbrock** [comment]
<a href="https://github.com/dbrock"><img src="https://avatars1.githubusercontent.com/u/14032?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dbrock](https://github.com/dbrock)**
_Friday Nov 24, 2017 at 03:09 GMT_

----

Also you might want to try disabling `ethrun` using `DAPP_NO_ETHRUN=1 dapp test` to run the test using only `hevm`

**Comment by mbrock** [comment]
<a href="https://github.com/HackFisher"><img src="https://avatars1.githubusercontent.com/u/1070122?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HackFisher](https://github.com/HackFisher)**
_Friday Nov 24, 2017 at 05:54 GMT_

----

Here is one information might be helpful:

https://github.com/ATNIO/atn-contracts/commit/e284911f3c606fa98bd9cf492f58eec6ec8a4b18

In the above commit, we can see that if the bytes data is "", it do not work, but if we change it to "0x", it pass the test without above error.

**Comment by mbrock** [comment]
<a href="https://github.com/dbrock"><img src="https://avatars1.githubusercontent.com/u/14032?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dbrock](https://github.com/dbrock)**
_Saturday Nov 25, 2017 at 09:56 GMT_

----

Could you please make a minimal test case demonstrating this problem?

That would make it much easier for us to know what is going on here.

In other words, make a new project and add as little code as possible to trigger this problem.

Thanks!
